trunk/swen610/swen610/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'swen610.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^toolshare/', include('toolshare.urls', namespace='toolshare')),
    url(r'^admin/', include(admin.site.urls)),
     (r'media/(?P<path>.*)', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

trunk/swen610/toolshare/urls.py
from django.conf.urls import patterns, url
from toolshare.views.base_controller import BaseController
from toolshare.views.user_controller import UserController
from toolshare.views.tool_controller import ToolController
from toolshare.views.shed_controller import ShedController
from toolshare.views.reservation_controller import ReservationController
from django.views.generic import TemplateView


urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='toolshare/index.html'), name='index'),
    url(r'^user-registration$', UserController.register_user, name='user-registration'),
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name': 'toolshare/login.html'} ,name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout',{'next_page': '/toolshare'}, name='logout'),
    url(r'^my_account$', UserController.my_account, name='my_account'),
    url(r'^change-personal-info$', UserController.change_personal_info, name='change-personal-info'),
    url(r'^create-shed$', ShedController.create_shed, name='create-shed'),
    url(r'^list-sheds$', ShedController.list_sheds, name='list-sheds'),
    url(r'^find_tool$', ToolController.find_tool, name='find_tool'),

    url(r'^change-preferences$', UserController.change_user_preferences, name='change-preferences'),
    url(r'^tool-registration$', ToolController.register_tool, name='tool-registration'),
    url(r'^list-owned-tools$', ToolController.list_owned_tools, name='list-owned-tools'),
    url(r'^borrow-tool/(\d+)$', ReservationController.borrow_tool, name='borrow-tool'),
    url(r'^tool-detail/(\d+)$', ToolController.tool_detail, name='tool-detail'),
    url(r'^change-tool-info/(\d+)$', ToolController.change_tool_info, name='change-tool-info'),
    url(r'^list-borrowed-tools/(?P<status>\w+)$', ReservationController.list_borrowed_tools, name='list-borrowed-tools'),
    url(r'^list-tool-arrangements/(?P<status>\w+)$', ReservationController.list_tool_arrangements, name='list-user-tools'),
    url(r'^testing$', TemplateView.as_view(template_name='toolshare/testing.html'), name='testing'),
    url(r'^change-tool-availability/(\d+)$', ToolController.change_availability_tool, name='change-tool-availability'),
    url(r'^reservation/(\d+)/cancel-as-borrower$', ReservationController.cancel_as_borrower, name='cancel-as-borrower'),
    url(r'^reservation/(\d+)/return-tool$', ReservationController.return_tool, name='return-tool'),
    url(r'^reservation/(\d+)/cancel-as-lender$', ReservationController.cancel_as_lender, name='cancel-as-lender'),
    url(r'^reservation/(\d+)/respond_reservation', ReservationController.respond_reservation, name='respond_reservation'),
    url(r'^reservation/(\d+)/ack-return-tool$', ReservationController.acknowledge_return_tool, name='ack-return-tool'),
    url(r'^statistics$', ReservationController.generate_statistics, name='statistics'),
    url(r'^activate-deactivate/(\d+)$', ToolController.activate_deactivate_tool, name='activate-deactivate'),


    # Deprecated URLs:
    # ----------------
    #url(r'^index$', TemplateView.as_view(template_name='toolshare/index.html'), name='index'),
    #url(r'^login$', UserController.login_user, name='login'),
    #url(r'^user-home', TemplateView.as_view(template_name='toolshare/user-home.html'), name='user-home'),
)

trunk/swen610/toolshare/forms/forms_shed.py
from django import forms
from toolshare.models.shed import Shed
import re


class ShedForm(forms.ModelForm):
    address = forms.CharField(required=True)
    #zipcode = forms.CharField(required=True)
    #city = forms.CharField(required=True)
    #state = forms.CharField(required=True)
    #coordinator = forms.CharField(required=True)
    class Meta:
        model = Shed
        exclude = ['coordinator']

    def __init__(self, *args, **kwargs):
        super(ShedForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(ShedForm, self).clean()
        address = cleaned_data.get("address")
        city = cleaned_data.get("city")
        zipcode = cleaned_data.get("zipcode")

        if address and address.strip() == '':
            msg = 'This field is required.'
            self._errors["address"] = self.error_class([msg])
            del cleaned_data["address"]

        if city and city.strip() == '':
            msg = 'This field is required.'
            self._errors["city"] = self.error_class([msg])
            del cleaned_data["city"]

        if zipcode and not re.search(r'^(\d{5}|\d{5}\-\d{4})$', zipcode):
            msg = 'The zip-code should follow the format XXXXX or XXXXX-XXXX: (e.g., 12345 and 12345-6789)'
            self._errors["zipcode"] = self.error_class([msg])
            del cleaned_data["zipcode"]

        return cleaned_data

trunk/swen610/toolshare/views/base_controller.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
class BaseController:
    @staticmethod
    def process_request(request, *args, **kwargs):
        return HttpResponse('Hello World...')

trunk/swen610/toolshare/views/reservation_controller.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from toolshare.models.tool import Tool
from toolshare.models.user import User
from toolshare.models.reservation import Reservation
from toolshare.views.base_controller import BaseController
from toolshare.forms.forms_tool import BorrowToolForm
from toolshare.utils import EmailSender
import datetime
from datetime import date, timedelta as td
from django.contrib import messages
from django.utils import timezone

# Create your views here.
class ReservationController(BaseController):
    PAGE_SIZE_BORROWED_TOOLS = 4

    @staticmethod
    @login_required
    def borrow_tool(request, tool_id):
        user = User.objects.get(pk=request.user.id)
        tool = Tool.objects.get(pk=tool_id)
        if request.method == 'POST':
            borrow_form = BorrowToolForm(request.POST, requested_tool_id=tool_id)

            if borrow_form.is_valid():
                new_reservation = borrow_form.save(commit=False)
                new_reservation.tool = tool
                new_reservation.borrower = user

                now = timezone.now()
                if new_reservation.start_date < now:
                    new_reservation.start_date = now

                if tool.shed is not None:
                    new_reservation.lender = tool.shed.coordinator
                    new_reservation.status = 'A'
                else:
                    new_reservation.lender = tool.owner
                    new_reservation.status = 'P'
                new_reservation.save()
                EmailSender.send_borrow_request_email(new_reservation)
                return redirect('/toolshare/list-borrowed-tools/all')
        else:
            # Show the Reservation-form
            borrow_form = BorrowToolForm(requested_tool_id=tool_id)

        # Get all the approved reservations
        now = datetime.datetime.now()
        reservations = Reservation.objects.filter(
            status = 'A',
            tool_id=tool_id,
            end_date__gt=now,
            start_date__lt=now + td(days=90)
        )

        list_disabled_dates = list()
        for reservation in reservations:
            delta = reservation.end_date - reservation.start_date
            for i in range(delta.days + 1):
                disable_date = reservation.start_date + td(days=i)
                list_disabled_dates.append(disable_date.strftime('%m/%d/%Y'))

        return render(request, 'toolshare/borrow-tool.html', {
            'tool': tool,
            'borrow_form': borrow_form,
            'tool_id': tool_id,
            'current_date': datetime.datetime.now().strftime('%m/%d/%Y'),
            'list_disabled_dates': list_disabled_dates
        })

    @staticmethod
    @login_required
    def list_borrowed_tools(request, status):
        if request.method == 'GET':
            user = User.objects.get(pk=request.user.id)
            if status == 'all':
                # Get all the reservations
                reservations = Reservation.objects.filter(
                    borrower_id = user.id,
                ).order_by('-id')
            elif status == 'pending':
                pass
            elif status == 'accepted':
                pass
            elif status == 'return-pending':
                pass
            elif status == 'return-ack':
                pass

            reservation_paginator = Paginator(reservations, ReservationController.PAGE_SIZE_BORROWED_TOOLS)
            page = request.GET.get('page')
            now_date = timezone.now()
            try:
                reservation_page = reservation_paginator.page(page)
            except PageNotAnInteger:
                reservation_page = reservation_paginator.page(1)
            except EmptyPage:
                # If page is out of range (e.g. 9999),
                # deliver last page of results.
                reservation_page = reservation_paginator.page(reservation_paginator.num_pages)

            return render(request, 'toolshare/list-borrowed-tools.html', {
                'reservation_page': reservation_page,
                'now_date':now_date
            })

    @staticmethod
    @login_required
    def list_tool_arrangements(request, status):
        if request.method == 'GET':
            user = User.objects.get(pk=request.user.id)
            if status == 'all':
                # Get all the reservations
                reservations = Reservation.objects.filter(
                    lender_id = user.id,
                ).order_by('-id')
            elif status == 'pending':
                pass
            elif status == 'accepted':
                pass
            elif status == 'return-pending':
                pass
            elif status == 'return-ack':
                pass

            reservation_paginator = Paginator(reservations, ReservationController.PAGE_SIZE_BORROWED_TOOLS)
            page = request.GET.get('page')
            try:
                reservation_page = reservation_paginator.page(page)
            except PageNotAnInteger:
                reservation_page = reservation_paginator.page(1)
            except EmptyPage:
                # If page is out of range (e.g. 9999),
                # deliver last page of results.
                reservation_page = reservation_paginator.page(reservation_paginator.num_pages)

            return render(request, 'toolshare/list-tool-arrangements.html', {
                'reservation_page': reservation_page
            })

    @staticmethod
    @login_required
    def cancel_as_borrower(request, reservation_id):
        if request.method == 'GET':
            user = User.objects.get(pk=request.user.id)
            reservation = Reservation.objects.get(pk=reservation_id)
            if request.user.id != reservation.borrower_id:
                messages.add_message(request, messages.WARNING, 'Oops. You are not allowed to change this reservation.')
                return redirect('/toolshare/list-borrowed-tools/all')
            else:
                # Cancel the borrower
                reservation.status = 'C'
                reservation.cancel_msg = 'The borrower cancelled the reservation.'
                reservation.save()
                messages.add_message(request, messages.SUCCESS, 'Your reservation was successfully cancelled.')
                return redirect('/toolshare/list-borrowed-tools/all')

    @staticmethod
    @login_required
    def return_tool(request, reservation_id):
        if request.method == 'GET':
            user = User.objects.get(pk=request.user.id)
            reservation = Reservation.objects.get(pk=reservation_id)
            if request.user.id != reservation.borrower_id:
                messagesadd_message(request, messages.WARNING, 'Oops. You are not allowed to change this reservation.')
                return redirect('/toolshare/list-borrowed-tools/all')
            else:
                now = timezone.now()
                if now < reservation.start_date:
                    messages.add_message(request, messages.WARNING, "Oops. You cannot return a tool that you don't have yet. Try cancelling the reservation.")
                else:
                    reservation.status = 'RP'
                    reservation.tool.status = 'R'
                    reservation.save()
                    reservation.tool.save()
                    messages.add_message(request, messages.SUCCESS, 'You returned the tool.')
                return redirect('/toolshare/list-borrowed-tools/all')

    @staticmethod
    @login_required
    def cancel_as_lender(request, reservation_id):
        if request.method == 'POST':
            user = User.objects.get(pk=request.user.id)
            reservation = Reservation.objects.get(pk=reservation_id)
            cancel_msg = request.POST['lender_message']
            if request.user.id != reservation.lender_id:
                messages.add_message(request, messages.WARNING, 'Oops. You are not allowed to change this reservation.')
            else:
                # Cancel the
                now = timezone.now()
                if reservation.start_date < now and now < reservation.end_date:
                    messages.add_message(request, messages.WARNING, 'The tool is currently being used by the borrower. You cannot cancel it.')
                else:
                    reservation.status = 'C'
                    reservation.cancel_msg = cancel_msg
                    reservation.save()
                    messages.add_message(request, messages.SUCCESS, 'The reservation was successfully cancelled.')
                    EmailSender.send_cancel_request_email(reservation)
            return redirect('/toolshare/list-tool-arrangements/all')

    @staticmethod
    @login_required
    def respond_reservation(request, reservation_id):
        if request.method == 'POST':
            #user = User.objects.get(pk=request.user.id)
            reservation = Reservation.objects.get(pk=reservation_id)
            if request.user.id != reservation.lender_id:
                messages.add_message(request, messages.WARNING, 'Oops. You are not allowed to change this reservation.')
            else:
                now = timezone.now()
                if reservation.end_date < now:
                    # Cancel automatically
                    reservation.status = 'C'
                    reservation.cancel_msg = 'Reservation was auto cancelled. The reservation date already passed'
                    messages.add_message(request, messages.ERROR, reservation.cancel_msg)
                elif 'button_approve' in request.POST:
                    # Approve
                    reservation.status = 'A'
                    reservation.tool.status = 'B'
                    messages.add_message(request, messages.SUCCESS, 'The reservation was Approved.')

trunk/swen610/toolshare/views/shed_controller.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from toolshare.models.shed import Shed
from toolshare.models.user import User
from toolshare.views.base_controller import BaseController
from toolshare.forms.forms_shed import ShedForm


# Create your views here.
class ShedController(BaseController):
    PAGE_SIZE = 10

    @staticmethod
    @login_required
    def create_shed(request):
        if request.method == 'POST':
            shedcreation_form = ShedForm(request.POST)
            if shedcreation_form.is_valid():
                # Generate the new-shed from the Form
                new_shed = shedcreation_form.save(commit=False)
                user = User.objects.get(pk=request.user.id)
                new_shed.coordinator=user
                new_shed.save()
                return redirect('/toolshare/list-sheds')
        else:
            shedcreation_form = ShedForm()

        return render(request, 'toolshare/create-shed.html',{
        'shedcreation_form': shedcreation_form
        })

    @staticmethod
    @login_required
    def list_sheds(request):
        if request.method == 'GET':
            user = User.objects.get(pk=request.user.id)
            user_sheds = user.shed_set.all()
            shed_paginator = Paginator(user_sheds, ShedController.PAGE_SIZE)

            page = request.GET.get('page')
            try:
                shed_page = shed_paginator.page(page)
            except PageNotAnInteger:
                shed_page = shed_paginator.page(1)
            except EmptyPage:
                # If page is out of range (e.g. 9999),
                # deliver last page of results.
                shed_page = shed_paginator.page(shed_paginator.num_pages)

            return render(request, 'toolshare/list-sheds.html',{
            'shed_page': shed_page,
            'user_sheds': user_sheds
            })

trunk/swen610/toolshare/views/stats_controller.py
from django.shortcuts import render
from toolshare.views.base_controller import BaseController

# Create your views here.
class StatsController(BaseController):
    pass

trunk/swen610/toolshare/templates/toolshare/base-user-home.html
{% extends "toolshare/base_home.html" %}
{% block title %}
| My account
{% endblock%}

{% block breadcrumb %}
    <li><a href="/toolshare/">Home</a></li><li class="active"><a href="#"></a>My account</li>
{% endblock %}

{% block main_heading %}
    <h2>My account</h2>
{% endblock %}

{% block content %}
        {% block actionbar_content%}
        <div class="actionbar">
            <div class="pull-left">
                <ul class="ext-tabs">
                    <li class="active"><a href="/toolshare/my_account"  onclick="window.open('/toolshare/my_account', '_self')">My information</a></li>
                    <li><a href="/toolshare/list-sheds" onclick="window.open('/toolshare/list-sheds', '_self')">Managed sheds</a></li>
                    <li><a href="/toolshare/list-owned-tools" onclick="window.open('/toolshare/list-owned-tools', '_self')">Owned Tools</a></li>
                </ul>
            </div>
        </div><!--actionbar-->
        {% endblock %}

        <div class="tab-content">
            {% block tab_content %}

            {% endblock%}
        </div><!--Actionbar end -->

{% endblock %}

trunk/swen610/toolshare/templates/toolshare/find_tool.html
{% extends "toolshare/base_home.html" %}

{% block title %}
| Find tool
{% endblock %}

{% block breadcrumb %}
<li><a href="/toolshare/">Home</a></li><li class="active"><a href="#"></a>Login</li>
{% endblock %}

{% block main_heading %}
<h2>Find tool</h2>
<p>Find a tool to borrow</p>
{% endblock %}

{% block content %}

{% if form.errors %}
<div class="alert alert-block alert-inline-top alert-dismissable" style="display:block;">
    <h4>Hmmm we couldn't log you in...</h4>
    {% if form.non_field_errors %}
    {{ form.non_field_errors }}
    {% else %}
    Check the error messages displayed below and try again.
    {% endif%}
    <button type="button" class="close" data-dismiss="alert">×</button>
</div>
{% endif %}

<div class="inner-padding"><!--inner padding-->

    <form method="get" action="/toolshare/find_tool">

        <div class="toolbar">
            <form method="get">
                <div class="toolbar-field">
                    <strong>Search for</strong>
                    <input class="form-control" name="search_for" required="" autofocus="" value="{{search_for}}" type="text" placeholder="Search for...">
                </div><!--
                                <div class="toolbar-field">
                                    <strong>Type</strong>
                                    <div class="simpelselect-container"><div class="simpelselect-inner"><div class="simpleselect-value">18 - 30</div><div class="simpleselect-btn"><i class="fa fa-caret-down"></i></div></div>
                                    <select class="form-control simpleselect">
                                        <option>Hammers</option>
                                        <option>Motorized tools</option>
                                        <option>Screwdrivers</option>
                                        <option>Other</option>
                                    </select></div>
                                </div>-->
                <div class="toolbar-field">
                    <strong>From</strong>
                    <input value='{{from_date}}' name="from_date" id="from_date" class="datepicker form-control" data-date-format="yyyy-mm-dd" type="text" />
                </div>
                <div class="toolbar-field">
                    <strong>To</strong>
                    <input value="{{to_date}}" name="to_date"  id="to_date" class="datepicker form-control" data-date-format="yyyy-mm-dd" type="text" />
                </div>
                <div class="toolbar-field">
                    <strong>&nbsp;</strong>
                    <button type="submit" name="find_tools" value ="find_tools" class="btn btn-default">Find tools</button>
                </div>
            </form>
        </div>

        {% for field in form %}
        <div class="row">
            <div class="col-sm-3"><label>{{field.label}}:</label></div>
            <div class="col-sm-9">

                {% if field.errors %}

                <div class="form-group has-error">
                    {% for error in field.errors %}
                        <label class="control-label" for="id_password">{{error}}</label>
                    {% endfor %}
                    {% else %}
                    <div class="form-group ">
                        {% endif %}
                        <div class="controls">{{ field }}</div>
                    </div><!--form group end-->

                </div>
            </div><!--col 9 end-->
            {% endfor %}
        </div><!-- row end-->
    </form>

    <div class="widget" >
        <header>
            <div class="pull-left">
                <h2>Tool results {{tool_count}}</h2>
            </div>
        </header>
        <div>
        <table class="table" data-rt-breakpoint="600" >
            <thead>
            <th class="th-square" scope="col"></th>
            <th class="th-user-date" scope="col">Details</th>
            <th class="th-square" scope="col">Reserve</th>
            </thead>
            <tbody>


            {% for tool in tool_page %}

            <tr>
                <td class="rt-hide-td">
                    <i class="fa" style="background:url(/toolshare/media/{{tool.picture}}) black no-repeat center center;height:78px;width:81px;"></i>
                    <p>{{tool.category}}</p>

                </td>
                <td class="rt-hide-td">
                    <p><strong>{{tool.name}}</strong></p>
                    <div class="spacer-5"></div>
                    <p class="text-muted">
                        {{tool.description}}
                    </p>
                </td>
                <td><a href="/toolshare/borrow-tool/{{tool.id}}" class="btn btn-info btn-sm"><i class="fa fa-pencil"></i>Reserve</a></td>
                <td class="rt-clone-td"><div class="rt-responsive-row"><div class="rt-responsive-th"></div><div class="rt-responsive-td">
                    <label><input type="checkbox"><span></span></label>
                </div></div><div class="rt-responsive-row"><div class="rt-responsive-th"></div><div class="rt-responsive-td">
                    <img src="images/users/user-1.jpg" alt="" class="td-avatar">
                </div></div><div class="rt-responsive-row"><div class="rt-responsive-th">User / Date</div><div class="rt-responsive-td">
                    <p><strong>Steven Watson</strong></p>
                    <div class="spacer-5"></div>
                    <p class="text-muted">November 24, 2012 at 11:45 am </p>
                </div></div><div class="rt-responsive-row"><div class="rt-responsive-th">Comment</div><div class="rt-responsive-td">
                    <p><strong>Quisque nec semper pulvinar pellentesque</strong></p>
                    <div class="spacer-5"></div>
                    <p class="text-muted">
                        Phasellus nibh neque, pharetra a augue nec, eleifend tempus erat.
                        Nam eros nibh, vestibulum at dolor eu, aliquet varius urna. Fusce iaculis odio viverra velit lobortis accumsan.
                        Curabitur id leo vitae sem sagittis tristique et in sapien.
                    </p>
                </div></div>
                </td></tr>

            {% endfor %}


            {% if tool_count == 0%}
                        <tr>
                            <td colspan="3">
                        <div class="alert alert-info">
                            <i class="fa fa-info-circle"></i>There are no records to show
                        </div>
                            </td>
                        </tr>
            {% endif %}

            </tbody>
        </table>
            </div>

        <div class="toolbar" >
            <div class="toolbar-field">
                <ul class="pagination pagination-centered">
                    {% if tool_page.has_previous %}
                    <li><a href="?search_for={{search_for}}&date_from={{date_from}}&date_to={{date_to}}&page=1"><< Prev</a></li>
                    <li><a href="?search_for={{search_for}}&date_from={{date_from}}&date_to={{date_to}}&page={{ tool_page.previous_page_number }}">< First</a></li>
                    {%else%}
                    <li><a style="color:#dddddd"><< First</a></li>
                    <li><a style="color:#dddddd">< Prev</a></li>
                    {% endif %}

                    {% for i in tool_page.paginator.page_range %}
                    {# {% if i <= tool_page.number|add:5 and i >= tool_page.number|add:-5%} #}
                    <li {% if tool_page.number == i %} class="active" {% endif %}><a href="?search_for={{search_for}}&date_from={{date_from}}&date_to={{date_to}}&page={{i}}">{{i}}</a></li>
                    {# {% endif %} #}

                    {% endfor %}

                    {% if tool_page.has_next %}
                    <li><a href="?search_for={{search_for}}&from_date={{from_date}}&to_date={{from_date}}&page={{tool_page.next_page_number}}">Next ></a></li>
                    <li><a href="?search_for={{search_for}}&from_date={{from_date}}&to_date={{from_date}}&page={{tool_page.paginator.num_pages }}">Last >></a></li>

                    {%else%}
                    <li><a style="color:#dddddd" class="disabled">Next ></a></li>
                    <li><a style="color:#dddddd" class="disabled">Last >></a></li>
                    {% endif %}
                </ul>
            </div>
        </div><!--toolbar end-->
    </div><!--widget end-->

</div><!--inner-padding end-->

{% endblock %}

trunk/swen610/toolshare/templates/toolshare/index.html
{% extends "toolshare/base_home.html" %}

{% block title %}
| Home
{% endblock %}

{% block breadcrumb %}
<li><a href="#"></a>Home</li>
{% endblock %}

{% block main_heading %}
<h2>Home</h2>
{% endblock %}

{% block content %}
	<div class="inner-padding">
	<div class="subheading">
    <h3>Welcome to tool share!</h3>
        </div>
	<p>
        {% if user.is_authenticated %}
            <p>Hello {{user.first_name}}!</p>
            <p>Are you here to list a tool or to borrow one? Which ever the case, just use the menu on your left.</p>
        {% else %}
            <a href="{% url 'toolshare:user-registration' %}">Register</a> now or
        	<a href="{% url 'toolshare:login' %}">Login</a> into your account.
        {% endif %}

	</p>

	</div><!--Inner padding end-->
{% endblock %}

trunk/swen610/toolshare/templates/toolshare/user-registration.html
{% extends "toolshare/base_home.html" %}

{% block title %}
| New user registration
{% endblock %}

{% block breadcrumb %}
<li><a href="/toolshare/">Home</a></li><li class="active"><a href="#"></a>Registration</li>
{% endblock %}

{% block main_heading %}
<h2>New user registration</h2>
<p>Create a new user account</p>
{% endblock %}

{% block content %}

    {% if form.errors %}
    <div class="alert alert-block alert-inline-top alert-dismissable" style="display:block;">
    <h4>It was not possible to register your user account...</h4>
    {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% else %}
        Check the error messages displayed below and try again.
        {% endif%}
        <button type="button" class="close" data-dismiss="alert">×</button>
    </div>
    {% endif %}

<div class="inner-padding" style="overflow:scroll">
    <form action="{%url 'toolshare:user-registration' %}" method="post">{% csrf_token %}
       {% for field in registration_form %}
            <div class="row">
                <div class="col-sm-3"><label>{{field.label}}:</label></div>
                <div class="col-sm-9">

                    {% if field.errors %}

                    <div class="form-group has-error">
                        {% for error in field.errors %}
                        <label class="control-label" for="id_password">{{error}}</label>
                        {% endfor %}
                        {% else %}
                        <div class="form-group ">
                            {% endif %}
                            <div class="controls">{{ field }}</div>
                        </div><!--form group end-->

                    </div>
                </div><!--Row end-->
                {% endfor %}

                <div class="row">

                    <div class="col-sm-3"></div>
                    <div class="col-sm-9">
                        <input type="submit" value="Register account" />
                    </div>
                </div>
    </form>
</div><!--inner padding end-->

{% endblock %}